config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get '/', :to => 'home#index'
  end

  namespace :admin do
    resources :home, only: [:index]
  end

  namespace :admin do
    resources :perguntas, except: [:show]
  end

  namespace :admin do
    resources :fotos, except: [:show]
  end

  namespace :admin do
    resources :inscritos
  end
  namespace :admin do
    resources :grupos
  end
  namespace :admin do
    resources :palestrantes, except: [:show]
  end

  devise_for :users, skip: [ :registration, :confirmations ]

  root to: 'home#index'

  resources :inscritos, only: [:index]
  resources :realizadores, only: [:index]
  resources :apoiadores, only: [:index]
  resources :grupos, only: [:index]
  resources :fotos, only: [:index]
  resources :palestrantes, only: [:index]
  resources :programacao, only: [:index]

end

app/models/grupo.rb
# == Schema Information
#
# Table name: grupos
#
#  id         :integer          not null, primary key
#  nome       :string(255)
#  quantidade :integer          default("0"), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Grupo < ApplicationRecord
	has_many :inscritos
	has_many :respostas, inverse_of: :grupo

	accepts_nested_attributes_for :respostas, reject_if: :all_blank, allow_destroy: true

	def name
		self.nome
	end
	
end

app/controllers/admin/grupos_controller.rb
class Admin::GruposController < Admin::ApplicationController
  before_action :set_grupo, only: [:show, :edit, :update, :destroy]

  # GET /admin/grupos
  # GET /admin/grupos.json
  def index
    @grupos = Grupo.all
  end

  # GET /admin/grupos/1
  # GET /admin/grupos/1.json
  def show
  end

  # GET /admin/grupos/new
  def new
    @grupo = Grupo.new
  end

  # GET /admin/grupos/1/edit
  def edit
  end

  # POST /admin/grupos
  # POST /admin/grupos.json
  def create
    @grupo = Grupo.new(grupo_params)

    respond_to do |format|
      if @grupo.save
        format.html { redirect_to admin_grupos_path, notice: 'Grupo criado com sucesso.' }
        format.json { render :show, status: :created, location: @grupo }
      else
        format.html { render :new }
        format.json { render json: @grupo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/grupos/1
  # PATCH/PUT /admin/grupos/1.json
  def update
    respond_to do |format|
      if @grupo.update(grupo_params)
        format.html { redirect_to admin_grupos_path, notice: 'Grupo atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @grupo }
      else
        format.html { render :edit }
        format.json { render json: @grupo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/grupos/1
  # DELETE /admin/grupos/1.json
  def destroy
    @grupo.destroy
    respond_to do |format|
      format.html { redirect_to admin_grupos_url, notice: 'Grupo deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grupo
      @grupo = Grupo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grupo_params
      params.require(:grupo).permit(:nome, respostas_attributes: [:id, :pergunta_id, :grupo_id, :resposta])
    end
end

app/controllers/grupos_controller.rb
class GruposController < ApplicationController
  def index
  	@grupos = Grupo.order(nome: :asc)
  end
end

app/helpers/admin/grupos_helper.rb
module Admin::GruposHelper
end

app/helpers/grupos_helper.rb
module GruposHelper
end

app/views/admin/grupos/_form.html.erb
<%= simple_form_for([:admin,@grupo]) do |f| %>
  <%= f.error_notification %>

  <%= f.input :nome %>
  <h4>Respostas</h4>
  <div id="respostas">
		<%= f.simple_fields_for :respostas do |resposta| %>
			<%= render 'resposta_fields', f: resposta %>
	  <% end %>
	  <div class="links">
	  	<%= link_to_add_association 'Add Resposta', f, :respostas %>
	  </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/grupos/_resposta_fields.html.erb
<div class=nested-fields>
	<%= f.input :pergunta_id, collection: Pergunta.all %>
	<%= f.input :resposta %>
	<%= link_to_remove_association "remove resposta", f %>
</div>

app/views/admin/grupos/edit.html.erb
<h2 class="titulo">Editando GT</h2>

<div class="row">
  <div class="col-md-12" style="text-align: right;">
    <%= link_to admin_grupos_path, class: "btn btn-default" do %>
      <i class="fa fa-chevron-left" aria-hidden="true"></i> Retornar
    <% end %>
  </div>
</div>

<%= render 'form' %>

app/views/admin/grupos/index.html.erb
<h2 class="titulo">Grupos de trabalhos (GT)</h2>

<div class="row">
  <div class="col-xs-12" style="text-align: right;">
    <%= link_to new_admin_grupo_path, class: "btn btn-default btn-xs" do %>
      <i class="fa fa-plus" aria-hidden="true"></i> Novo GT
    <% end %>
  </div>
</div>

<table class="table table-condensed">
  <thead>
    <tr>
      <th>#</th>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grupos.each do |grupo| %>
      <tr>
        <td><%= grupo.id %></td>
        <td><%= grupo.nome %></td>
        <td class="table-link"><%= link_to_show [:admin,grupo] %></td>
        <td class="table-link"><%= link_to_edit edit_admin_grupo_path(grupo) %></td>
        <td class="table-link"><%= link_to_destroy [:admin,grupo]%></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/grupos/new.html.erb
<h2 class="titulo">Incluindo GT</h2>

<div class="row">
  <div class="col-md-12" style="text-align: right;">
    <%= link_to admin_grupos_path, class: "btn btn-default" do %>
      <i class="fa fa-chevron-left" aria-hidden="true"></i> Retornar
    <% end %>
  </div>
</div>

<%= render 'form' %>

app/views/admin/grupos/show.html.erb
<h2 class="titulo">Visualizando Grupo</h2>

<div class="row">
  <div class="col-md-12" style="text-align: right;">
    <%= link_to edit_admin_grupo_path(@grupo), class: "btn btn-default" do %>
      <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Editar
    <% end %>
    <%= link_to admin_grupos_path, class: "btn btn-default" do %>
      <i class="fa fa-chevron-left" aria-hidden="true"></i> Retornar
    <% end %>
  </div>
</div>

<p>
  <strong>Nome:</strong>
  <%= @grupo.nome %>
</p>
<br/>

<h4>Perguntas/Respostas</h4>

<% @grupo.respostas.each do |resposta| %>
<div class="row">
  <div class="col-xs-12" style="font-weight: bold;"><%= resposta.pergunta.pergunta %></div>
  <div class="col-xs-12">
    <ul>
      <li>Resp: <%= resposta.resposta %></li>
    </ul>
  </div>
</div>
<% end %>