config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get '/', :to => 'home#index'
  end

  namespace :admin do
    resources :home, only: [:index]
  end

  namespace :admin do
    resources :perguntas, except: [:show]
  end

  namespace :admin do
    resources :fotos, except: [:show]
  end

  namespace :admin do
    resources :inscritos
  end
  namespace :admin do
    resources :grupos
  end
  namespace :admin do
    resources :palestrantes, except: [:show]
  end

  devise_for :users, skip: [ :registration, :confirmations ]

  root to: 'home#index'

  resources :inscritos, only: [:index]
  resources :realizadores, only: [:index]
  resources :apoiadores, only: [:index]
  resources :grupos, only: [:index]
  resources :fotos, only: [:index]
  resources :palestrantes, only: [:index]
  resources :programacao, only: [:index]

end

app/models/inscrito.rb
# == Schema Information
#
# Table name: inscritos
#
#  id                :integer          not null, primary key
#  nome              :string(255)
#  endereco          :string(255)
#  complemento       :string(255)
#  bairro            :string(255)
#  cidade            :string(255)
#  estado            :string(255)
#  cep               :string(255)
#  fone              :string(255)
#  celular           :string(255)
#  instituicao       :string(255)
#  grupo_id          :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  foto_file_name    :string(255)
#  foto_content_type :string(255)
#  foto_file_size    :integer
#  foto_updated_at   :datetime
#  email             :string(255)
#
# Indexes
#
#  index_inscritos_on_grupo_id  (grupo_id)
#

class Inscrito < ApplicationRecord
	before_create :selecionaGrupo
	belongs_to :grupo
	
	has_attached_file :foto, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/:style/missing.png"
  validates_attachment_content_type :foto, content_type: /\Aimage\/.*\z/         
	crop_attached_file :foto


	def selecionaGrupo
		gt = Grupo.order(:quantidade).first
		self.grupo = gt
		gt.quantidade = gt.quantidade + 1
		gt.save
	end
end

app/controllers/admin/inscritos_controller.rb
class Admin::InscritosController < Admin::ApplicationController
  before_action :set_inscrito, only: [:show, :edit, :update, :destroy]

  # GET /admin/inscritos
  # GET /admin/inscritos.json
  def index
    @inscritos = Inscrito.all.order(:nome).paginate(:page => params[:page], :per_page => 10)
  end

  # GET /admin/inscritos/1
  # GET /admin/inscritos/1.json
  def show
  end

  # GET /admin/inscritos/new
  def new
    @inscrito = Inscrito.new
    @estados = ['AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO']
    @grupos = Grupo.all
  end

  # GET /admin/inscritos/1/edit
  def edit
    @estados = ['AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO']
    @grupos = Grupo.all
  end

  # POST /admin/inscritos
  # POST /admin/inscritos.json
  def create
    @inscrito = Inscrito.new(inscrito_params)

    if @inscrito.save
      testar_email
      flash[:notice] = "Inscrição efetuada com sucesso."
      if inscrito_params[:foto].blank?
        redirect_to [:admin,@inscrito]
      else
        render :action => 'crop'
      end
    else
      render :action => 'new'
    end

  end

  # PATCH/PUT /admin/inscritos/1
  # PATCH/PUT /admin/inscritos/1.json
  def update
    if @inscrito.update_attributes(inscrito_params)
      testar_email
      flash[:notice] = "Inscrição atualizada com sucesso."
      if inscrito_params[:foto].blank?
        redirect_to [:admin,@inscrito]
      else
        render :action => 'crop'
      end
    else
      render :action => 'edit'
    end
  end

  def update_crop
    if @inscrito.update_attributes(inscrito_params)
      flash[:notice] = "Inscrição atualizada com sucesso."
      redirect_to [:admin,@inscrito]
    else
      render :action => 'edit'
    end
  end

  # DELETE /admin/inscritos/1
  # DELETE /admin/inscritos/1.json
  def destroy
    @inscrito.destroy
    respond_to do |format|
      format.html { redirect_to admin_inscritos_url, notice: 'Inscrição deletada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private

    def testar_email
      if inscrito_params[:email].length>10 && User.find_by_email(inscrito_params[:email]).nil?
        generated_password = Devise.friendly_token.first(8)
        user = User.create!(:email => inscrito_params[:email], :admin => false, :password => generated_password)
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_inscrito
      @inscrito = Inscrito.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inscrito_params
      params.require(:inscrito).permit(:nome, :email, :endereco, :complemento, :bairro, :cidade, :estado, :cep, :fone, :celular, :foto,
          :grupo, :grupo_id,
          :foto, 
          :foto_original_w, 
          :foto_original_h,
          :foto_crop_x, 
          :foto_crop_y, 
          :foto_crop_w, 
          :foto_crop_h,
          :foto_box_w, :foto_aspect)
    end
end

app/controllers/inscritos_controller.rb
class InscritosController < ApplicationController
  def index
  	@inscritos = Inscrito.all.order(:nome).paginate(:page => params[:page], :per_page => 5)
  end
end

app/helpers/admin/inscritos_helper.rb
module Admin::InscritosHelper
end

app/helpers/inscritos_helper.rb
module InscritosHelper
end

app/views/admin/inscritos/_form.html.erb
<%= simple_form_for([:admin,@inscrito]) do |f| %>
  <%= f.error_notification %>

  <%= f.file_field :foto %>
  <%= f.input :nome %>
  <%= f.input :endereco %>
  <%= f.input :complemento %>
  <%= f.input :bairro %>
  <%= f.input :cidade %>
  <%= f.input :estado, collection: @estados, prompt: 'Selecione o estado' %>
  <%= f.input :cep %>
  <%= f.input :fone %>
  <%= f.input :celular %>
  <%= f.input :email %>
  <%= f.input :grupo_id, collection: @grupos, prompt: 'Selecione o grupo' %>
  
  <div class="form-actions">
    <%= f.button :submit %>
  </div>

<% end %>

app/views/admin/inscritos/crop.html.erb
<%= form_for [:admin,@inscrito] do |f| %>
	<input type="hidden" name="cropping" value="ok">
	<div class="row">
		<div class="col-xs-12">
  		<%= f.cropbox :foto, :width => 300 %>
		</div>
	</div>
	<br/><br/>
	<div class="row">
		<div class="col-sm-12">
  		<%= f.crop_preview :foto, :width => 100 %>
		</div>
	</div>
	<br/><br/>
	<div class="row">
		<div class="col-sm-12">
  			<%= f.submit 'Salvar Foto' %>
		</div>
	</div>
<% end %>

app/views/admin/inscritos/edit.html.erb
<h2 class="titulo">Editar Inscrição</h2>

<div class="row">
  <div class="col-md-12" style="text-align: right;">
    <%= link_to [:admin,@inscrito], class: "btn btn-default" do %>
      <i class="fa fa-building-o" aria-hidden="true"></i> Visualizar
    <% end %>
    <%= link_to admin_inscritos_path, class: "btn btn-default" do %>
      <i class="fa fa-chevron-left" aria-hidden="true"></i> Retornar
    <% end %>
  </div>
</div>

<%= render 'form' %>

app/views/admin/inscritos/index.html.erb
<h2 class="titulo">Inscrição</h2>
<div class="row">

<div class="row">
  <div class="col-xs-12" style="text-align: center;">
    <%= pagination @inscritos %><br/>
    <%= page_entries_info @inscritos %>    
  </div>
</div>

<div class="row">
  <div class="col-xs-12" style="text-align: right;">
    <%= link_to new_admin_inscrito_path, class: "btn btn-default btn-xs" do %>
      <i class="fa fa-plus" aria-hidden="true"></i> Nova Inscrição
    <% end %>
  </div>
</div>

<% @inscritos.each do |inscrito| %>
  <div class="media bottom-line" style="font-size: 85%;">
    <div class="media-left">
      <a href="#">
        <%= image_tag inscrito.foto.url(:thumb), class: "media-object", alt: inscrito.nome %>
      </a>
    </div>
    <div class="media-body">
      <h4 class="media-heading"><%= inscrito.nome %></h4>
        <div class="row">
          <div class="col-sm-12">
            Grupo: <%= inscrito.grupo.nome %>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-12">
            Estado: <%= inscrito.estado %>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-6 col-md-3">
            Fone: <%= inscrito.fone %>
          </div>
          <div class="col-sm-6 col-md-3">
            Celular: <%= inscrito.celular %>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-12">
            email: <%= inscrito.email %>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-4 col-md-2">
            <%= link_to_show([:admin,inscrito],true) %>
          </div>
          <div class="col-sm-4 col-md-2">
            <%= link_to_edit(edit_admin_inscrito_path(inscrito),true) %>
          </div>
          <div class="col-sm-4 col-md-2">
            <%= link_to_destroy([:admin,inscrito],true) %>
          </div>
        </div>
    </div>
  </div>
<% end %>
<br/>
<div class="row">
  <div class="col-sm-12" style="text-align: center">
    <%= pagination @inscritos %>
  </div>
</div>

<br>

app/views/admin/inscritos/new.html.erb
<h2>Nova Inscrição</h2>

<div class="row">
  <div class="col-md-12" style="text-align: right;">
    <%= link_to admin_inscritos_path, class: "btn btn-default" do %>
      <i class="fa fa-chevron-left" aria-hidden="true"></i> Retornar
    <% end %>
  </div>
</div>

<%= render 'form' %>

app/views/admin/inscritos/show.html.erb
  <div class="media bottom-line" style="font-size: 85%;">
    <div class="media-left">
      <a href="#">
        <%= image_tag @inscrito.foto.url(:medium), class: "media-object", alt: @inscrito.nome %>
      </a>
    </div>
    <div class="media-body">
      <h4 class="media-heading"><%= @inscrito.nome %></h4>
      <div class="row">
        <div class="col-sm-12">
          Grupo: <%= @inscrito.grupo.nome %>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12">
          Estado: <%= @inscrito.estado %>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-6 col-md-3">
          Fone: <%= @inscrito.fone %>
        </div>
        <div class="col-sm-6 col-md-3">
          Celular: <%= @inscrito.celular %>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12">
          Endereço: <%= @inscrito.endereco %>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12">
          Complemento: <%= @inscrito.complemento %>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12">
          Cidade/UF: <%= @inscrito.cidade+'/'+@inscrito.estado %>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12">
          cep: <%= @inscrito.cep %>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12">
          email: <%= @inscrito.email %>
        </div>
      </div>
      <br/>
      <div class="row">
        <div class="col-md-12">
          <%= link_to edit_admin_inscrito_path(@inscrito), class: "btn btn-default" do %>
            <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Editar
          <% end %>
          <%= link_to admin_inscritos_path, class: "btn btn-default" do %>
            <i class="fa fa-chevron-left" aria-hidden="true"></i> Retornar
          <% end %>
        </div>
      </div>


      </div>
  </div>
  </div>